--- !Config
save_to_file: ""
wikitext: !WikitextConfig
  # 对日语歌词额外处理（去除多余的换行）
  process_lyrics_jap: true
  # 检测歌词中的括号，如果括号中都是平假名而且括号前有汉字，将括号中内容
  # 视为注音并添加photrans模板。
  furigana_local: true
  # 从Yahoo，vocadb，Vocaloid Lyrics Wiki等网站获取振假名；暂时没有效果
  furigana_all: true
  # 检测不到AtWiki的中文翻译后直接放弃，减少使用难度
  lyrics_chs_fail_fast: true
  # 是否询问投稿文
  uploader_note: false
  # 是否检测P主模板和分类
  producer_template_and_cat: true
color: !ColorConfig
  # 让用户从图片选择背景颜色
  color_from_image: true
  # 如果指定了背景颜色，但是文字颜色没有指定，亮度（0-100）高达多少会使用黑色文字？
  fg_color_threshold: 60
  # 打开森雨亮瞎眼模式；功能未知；副作用未知
  senyu_mode: false
image: !ImageConfig
  # 下载封面
  download_cover: false
  # 下载所有封面然后选择分辨率最大的（不建议开启；niconico的封面大但是很糊）
  download_all: false
  # 自动裁剪封面黑边
  crop: true
  # 剪裁判断值，数字越高剪裁力度越大。建议设为0-50避免误伤封面。
  crop_threshold: 20
  # 自动上传图片至萌娘共享
  auto_upload: false
