--- !Config
save_to_file: ""
# 选择程序语言。zh为中文，en是英文。注意：部分内容没有被汉化。
lang: "zh"
# 当vocadb有重名歌曲，且程序默认选择错误的曲目时启用此项
vocadb_manual: false
# 自定义输出文件夹，如果留空则让程序自行选择默认文件夹
# （理论上）支持任意操作系统的任意路径，例如"~/Documents/萌百"或"D:\萌百"或"output2"
output_dir: ""
# 自定义代理的ip地址，格式是http://127.0.0.1:<端口号>
# 如果不使用代理请留空
proxies: ""
wikitext: !WikitextConfig
  # 对日语歌词额外处理（去除多余的换行）
  process_lyrics_jap: true
  # 检测歌词中的括号，如果括号中都是平假名而且括号前有汉字，将括号中内容
  # 视为注音并添加photrans模板。
  furigana_local: true
  # 从Yahoo，vocadb，Vocaloid Lyrics Wiki等网站获取振假名；暂时没有效果
  furigana_all: false
  # 所有歌词留空，并默认填写AtWiki为翻译源（定制选项，慎用）
  no_lyrics: false
  # 检测不到AtWiki的中文翻译后直接放弃，减少使用难度
  lyrics_chs_fail_fast: true
  # 是否询问投稿文
  uploader_note: false
  # 是否检测P主模板和分类
  producer_template_and_cat: false
color: !ColorConfig
  # 让用户从封面图片选择背景颜色（需要打开image.download_cover）
  color_from_image: true
  # 如果指定了背景颜色，但是文字颜色没有指定，亮度（0-100）高达多少会使用黑色文字？
  fg_color_threshold: 60
  # 打开森雨亮瞎眼模式；功能未知；副作用未知
  senyu_mode: false
image: !ImageConfig
  # 下载封面
  download_cover: false
  # 下载所有视频网站的封面
  download_all: false
  # 自动裁剪封面黑边
  crop: true
  # 默认剪裁判断值，数字越高剪裁力度越大。建议设为0-50避免误伤封面。
  crop_threshold: 20
  # 自动上传图片至萌娘共享
  auto_upload: false
