--- !Config
wikitext: !WikitextConfig
  # 对日语歌词额外处理（注音，去除多余的换行）
  process_lyrics_jap: true
  # 检测不到AtWiki的中文翻译后直接放弃，减少使用难度；暂时没有效果
  lyrics_chs_fail_fast: false
  # 是否询问投稿文
  uploader_note: false
color: !ColorConfig
  # 让用户从图片选择背景颜色
  color_from_image: false
  # 如果指定了背景颜色，但是文字颜色没有指定，亮度（0-100）高达多少会使用黑色文字？
  fg_color_threshold: 60
  # 打开森雨亮瞎眼模式；功能未知；副作用未知
  senyu_mode: false
image: !ImageConfig
  # 下载所有封面然后选择分辨率最大的（不建议开启；niconico的封面大但是很糊）
  download_all: false
  # 自动裁剪封面黑边
  crop: true
  # 剪裁判断值，数字越高剪裁力度越大。建议设为0-50避免误伤封面。
  crop_threshold: 20
